### ISSUE TITLE
Kaiji malware

### ISSUE THREAD

**Issue by dkragen** [flathub/xyz.rescribe.rescribe#3]
Clamav found Kaiji unix malicious go packages in Rescribe:

/var/lib/flatpak/app/xyz.rescribe.rescribe/x86_64/stable/583d051d751e3a8e332528a299fcc6186762e4fc991217006af3c7f9efa32a0b/files/bin/rescribe-bin-wayland: Unix.Malware.Kaiji-10003916-0 FOUND

/var/lib/flatpak/app/xyz.rescribe.rescribe/x86_64/stable/583d051d751e3a8e332528a299fcc6186762e4fc991217006af3c7f9efa32a0b/files/bin/rescribe-bin: Unix.Malware.Kaiji-10003916-0 FOUND

**Comment by nickjwhite** [comment]
Thanks for the report @dkragen. This is a false positive. From a quick web search it looks like the ClamAV rule for Kaiji was not well-written so incorrectly matched a lot of different programs built with Go (like Rescribe). It has been pulled from their database for now, by the looks of it. For more details see this thread: https://github.com/Cisco-Talos/clamav/issues/944

**Comment by dkragen** [comment]
Hello Mr. White,

Thank you for the followup. I also read through that thread. Ugh. False
positives are annoying. Anyway glad to hear that the flatpaks that lit up
yesterday are all ok.

Best,

DKragen

On Thu, 08 Jun 2023 01:55:14 -0700, Nick White wrote:

> Thanks for the report @dkragen. This is a false positive. From a quick
web search it looks like the ClamAV rule for Kaiji was not well-written
so incorrectly matched a lot of different programs built with Go (like
Rescribe). It has been pulled from their database for now, by the looks
of it. For more details see this thread:
https://github.com/Cisco-Talos/clamav/issues/944
