### ISSUE TITLE
Install additional models

### ISSUE THREAD

**Issue by maymage** [flathub/xyz.rescribe.rescribe#4]
Trying to add new language models from the language/script dropdown 
doesn't seem to work, although I downloaded one from 

https://rescribe.xyz/rescribe/trainings.html

to a folder to which the program has access.

**Comment by nickjwhite** [comment]
Hi @maymage, thanks for reporting. Can you give a bit more information on what isn't working, please?

What *should* happen is the following: When you click on "Other" in the dropdown, it should open the file browser, from which you can select a `.traineddata` file and click "open". Once you've done that, the name of your downloaded model should be shown in the dropdown list, and then when you click "Start OCR" it will use it. What step is failing?

Or is the issue that it all appears to work but the results aren't what you'd expect from the training you chose? If that's the case, can you attach one of the `.hocr` output files so I can take a look?

Thanks again, I look forward to hearing back from you.

**Comment by maymage** [comment]
> What should happen is the following: When you click on "Other" in the dropdown, it should open the file browser, from which you can select a .traineddata file and click "open"

So far so good.. 

> Once you've done that, the name of your downloaded model should be shown in the dropdown list,

But this fails.. it's not in the dropdown list. I specifically tried to install the modern french model.

**Comment by nickjwhite** [comment]
> > Once you've done that, the name of your downloaded model should be shown in the dropdown list,
> 
> But this fails.. it's not in the dropdown list. I specifically tried to install the modern french model.

Ah, you're right, I just reproduced it! Short-term, you could try the non-flatpak version from https://rescribe.xyz/rescribe as that works, but I'll look into what's going wrong and update here when I have an update.

**Comment by nickjwhite** [comment]
Hi @maymage, I finally found the time to look into this, and have found the issue and [fixed it upstream]( https://github.com/rescribe/bookpipeline/commit/d2399a7ce0af49098a065c48409d1512f37c7c21). I'll make a new release in the next few days, including the flatpak, which should fix this for you. Please do test it once I make the release, and let me know if anything is still up (but I've tested on my end and it definitely seems to be sorted).

**Comment by nickjwhite** [comment]
The flatpak v1.2.0 release is now out, and should fix this. Please re-open this issue if it still affects you.
